// Stub build_options for standalone example builds (zig build-exe).
// When using `zig build` from the repo root, the real build_options module is
// generated by the build system.  This file is only needed when invoking
// zig build-exe directly from the examples/ directory.
pub const macos_fsevents = false;
pub const install_tests = false;
